import type { Patient, MeasurementSession, ChartEntry, RomPoint } from "./types";
import { generateFullRomCurve } from "./measurement";
import { stretchingLibrary } from "./stretching-library";

export const mockPatientsNew: Patient[] = [
  { id: "P-01", name: "김OO", age: 46, sex: "남", heightCm: 172, weightKg: 78, mainComplaint: "우측 손목 통증 및 가동 범위 제한", assumedDiagnosis: "수근관절염, de Quervain 협착성 건막염 의심 (M65.4)" },
  { id: "P-02", name: "이OO", age: 39, sex: "여", heightCm: 162, weightKg: 56, mainComplaint: "좌측 어깨 통증 및 운동 시 악화", assumedDiagnosis: "견봉하 충돌 증후군 (M75.1)" },
  { id: "P-03", name: "박OO", age: 57, sex: "여", heightCm: 158, weightKg: 62, mainComplaint: "허리 통증, 야간통, 근력 저하", assumedDiagnosis: "요추 추간판 탈출증, L4/L5 (M51.1)" },
  { id: "P-04", name: "최OO", age: 32, sex: "남", heightCm: 178, weightKg: 82, mainComplaint: "우측 무릎 통증 및 움직임 불안정", assumedDiagnosis: "슬관절 반월판 손상 의심 (M23.2)" },
  { id: "P-05", name: "정OO", age: 51, sex: "여", heightCm: 155, weightKg: 58, mainComplaint: "좌측 발목 통증 및 저림", assumedDiagnosis: "족관절 만성 인대 불안정성 (M25.3)" },
];

function makeCurve(rom: number): RomPoint[] {
  return generateFullRomCurve(rom, 60);
}

export const mockMeasurementSessions: MeasurementSession[] = [
  {
    id: "session-P-01-1",
    patientId: "P-01",
    measuredAt: "2026-06-25T10:30:00",
    clinicianName: "임상의 (데모)",
    diagnosisCode: "M65.4",
    wearLocation: "wrist",
    motionType: "wrist_flexion_extension",
    laterality: "우측",
    attachmentMethod: "피부 부착",
    deviceConnected: true,
    sensorLabel: "ACU-S01",
    preRom: 42,
    postRom: 59,
    prePainNrs: 6,
    postPainNrs: 3,
    preCurve: makeCurve(42),
    postCurve: makeCurve(59),
    smoothnessScore: 78,
    stabilityScore: 82,
    confidenceScore: 91,
    symptoms: ["통증", "가동 범위 제한", "뻣뻣함"],
    clinicalSummary: "치료 전 우측 손목 굴곡/신전 ROM 42°에서 치료 후 59°로 17° 향상(+40.5%). 통증 NRS 6→3으로 유의미한 개선. 움직임 유연성(78점)과 안정성(82점) 양호. de Quervain 협착성 건막염(M65.4) 의심하에 초음파 검사 권장.",
    patientSummary: "오늘 치료 후 손목 움직임 범위가 42°에서 59°로 넓어졌습니다. 통증도 6점에서 3점으로 줄었습니다. 꾸준한 스트레칭을 통해 더욱 회복될 수 있습니다.",
    stretchingPlan: {
      id: "sp-P-01-1",
      sessionId: "session-P-01-1",
      targetArea: "wrist",
      title: "손목 회복 스트레칭 프로그램",
      description: "치료 후 손목 가동 범위 유지 및 근육 이완을 위한 홈 스트레칭 계획입니다. 하루 2회(아침, 저녁) 시행을 권장합니다.",
      exercises: stretchingLibrary.wrist,
      generalCautions: ["통증이 심해지면 즉시 중단하고 담당 한의사에게 알려주세요.", "스트레칭 전 가볍게 온열 찜질을 하면 효과적입니다."],
    },
    reportId: "report-session-P-01-1",
    chartStatus: "approved",
  },
  {
    id: "session-P-02-1",
    patientId: "P-02",
    measuredAt: "2026-06-24T14:15:00",
    clinicianName: "임상의 (데모)",
    diagnosisCode: "M75.1",
    wearLocation: "shoulder",
    motionType: "shoulder_abduction",
    laterality: "좌측",
    attachmentMethod: "스트랩 착용",
    deviceConnected: true,
    sensorLabel: "ACU-S02",
    preRom: 118,
    postRom: 146,
    prePainNrs: 7,
    postPainNrs: 4,
    preCurve: makeCurve(118),
    postCurve: makeCurve(146),
    smoothnessScore: 85,
    stabilityScore: 79,
    confidenceScore: 88,
    symptoms: ["통증", "가동 범위 제한", "운동 시 악화"],
    clinicalSummary: "좌측 어깨 외전 ROM이 치료 전 118°에서 치료 후 146°로 28° 향상(+23.7%). 통증 NRS 7→4. 견봉하 충돌 증후군(M75.1) 소견으로 체외충격파(ESWT) 지속 및 도수 관절가동술 병행 권장.",
    patientSummary: "오늘 치료 후 어깨를 들어 올릴 수 있는 각도가 118°에서 146°로 늘었습니다. 통증도 7점에서 4점으로 줄었습니다. 집에서 꾸준히 스트레칭을 해주시면 더 빨리 좋아질 수 있습니다.",
    stretchingPlan: {
      id: "sp-P-02-1",
      sessionId: "session-P-02-1",
      targetArea: "shoulder",
      title: "어깨 회복 스트레칭 프로그램",
      description: "치료 후 어깨 가동 범위 유지를 위한 홈 스트레칭 계획입니다.",
      exercises: stretchingLibrary.shoulder,
      generalCautions: ["팔을 무리하게 올리지 마세요.", "통증이 악화되면 한의사에게 알려주세요."],
    },
    reportId: "report-session-P-02-1",
    chartStatus: "not_reviewed",
  },
  {
    id: "session-P-03-1",
    patientId: "P-03",
    measuredAt: "2026-06-23T09:00:00",
    clinicianName: "임상의 (데모)",
    diagnosisCode: "M51.1",
    wearLocation: "lowerBack",
    motionType: "lumbar_flexion",
    laterality: "양측",
    attachmentMethod: "의복 위 부착",
    deviceConnected: true,
    sensorLabel: "ACU-S03",
    preRom: 38,
    postRom: 52,
    prePainNrs: 8,
    postPainNrs: 5,
    preCurve: makeCurve(38),
    postCurve: makeCurve(52),
    smoothnessScore: 62,
    stabilityScore: 58,
    confidenceScore: 74,
    symptoms: ["통증", "뻣뻣함", "야간통", "근력 저하"],
    clinicalSummary: "요추 굴곡 ROM 38°→52°(+36.8%). 통증 NRS 8→5. 움직임 유연성 62점, 안정성 58점으로 개선 여지 있음. L4-L5 추간판 탈출증 소견 하에 도수치료 지속, MRI 추적 검사 권장.",
    patientSummary: "오늘 치료 후 허리를 구부릴 수 있는 각도가 38°에서 52°로 늘었습니다. 통증도 8점에서 5점으로 줄었습니다. 야간통 및 저림 증상 지속 시 의사 상담을 권장합니다.",
    stretchingPlan: {
      id: "sp-P-03-1",
      sessionId: "session-P-03-1",
      targetArea: "lowerBack",
      title: "허리 회복 스트레칭 프로그램",
      description: "요추 가동 범위 회복 및 근육 이완을 위한 홈 스트레칭 계획입니다.",
      exercises: stretchingLibrary.lowerBack,
      generalCautions: ["급격한 동작은 피하세요.", "저림이나 방사통이 생기면 즉시 중단하세요."],
    },
    reportId: "report-session-P-03-1",
    chartStatus: "not_reviewed",
  },
  {
    id: "session-P-04-1",
    patientId: "P-04",
    measuredAt: "2026-06-25T11:00:00",
    clinicianName: "임상의 (데모)",
    diagnosisCode: "M23.2",
    wearLocation: "knee",
    motionType: "knee_flexion",
    laterality: "우측",
    attachmentMethod: "스트랩 착용",
    deviceConnected: true,
    sensorLabel: "ACU-S04",
    preRom: 96,
    postRom: 121,
    prePainNrs: 5,
    postPainNrs: 2,
    preCurve: makeCurve(96),
    postCurve: makeCurve(121),
    smoothnessScore: 88,
    stabilityScore: 91,
    confidenceScore: 94,
    symptoms: ["통증", "가동 범위 제한", "움직임 불안정"],
    clinicalSummary: "우측 무릎 굴곡 ROM 96°→121°(+26.0%). 통증 NRS 5→2로 현저한 호전. 안정성 91점으로 양호. 반월상 연골 손상 의심으로 MRI 확인 및 기능적 재활 운동 강화 권장.",
    patientSummary: "오늘 치료 후 무릎을 구부릴 수 있는 각도가 96°에서 121°로 늘었습니다. 통증도 5점에서 2점으로 크게 줄었습니다. 꾸준한 재활이 중요합니다.",
    stretchingPlan: {
      id: "sp-P-04-1",
      sessionId: "session-P-04-1",
      targetArea: "knee",
      title: "무릎 회복 스트레칭 프로그램",
      description: "무릎 가동 범위 회복 및 주변 근육 강화를 위한 홈 프로그램입니다.",
      exercises: stretchingLibrary.knee,
      generalCautions: ["무릎에 체중을 실을 때 주의하세요.", "붓기나 열감이 있으면 즉시 알려주세요."],
    },
    reportId: "report-session-P-04-1",
    chartStatus: "not_reviewed",
  },
  {
    id: "session-P-05-1",
    patientId: "P-05",
    measuredAt: "2026-06-22T15:30:00",
    clinicianName: "임상의 (데모)",
    diagnosisCode: "M25.3",
    wearLocation: "ankle",
    motionType: "ankle_dorsi_plantar",
    laterality: "좌측",
    attachmentMethod: "스트랩 착용",
    deviceConnected: true,
    sensorLabel: "ACU-S05",
    preRom: 11,
    postRom: 18,
    prePainNrs: 4,
    postPainNrs: 2,
    preCurve: makeCurve(11),
    postCurve: makeCurve(18),
    smoothnessScore: 55,
    stabilityScore: 61,
    confidenceScore: 68,
    symptoms: ["통증", "저림", "뻣뻣함", "운동 시 악화"],
    clinicalSummary: "좌측 발목 배굴/저굴 ROM 11°→18°(+63.6%). 통증 NRS 4→2. 유연성 55점, 안정성 61점으로 계속 관리 필요. 족관절 만성 인대 불안정성(M25.3)으로 고유감각(proprioception) 훈련 및 기능적 테이핑(functional taping) 병행 권장.",
    patientSummary: "오늘 치료 후 발목 움직임 범위가 11°에서 18°로 늘었습니다. 통증도 4점에서 2점으로 줄었습니다. 발목 안정성 강화를 위한 꾸준한 운동이 필요합니다.",
    stretchingPlan: {
      id: "sp-P-05-1",
      sessionId: "session-P-05-1",
      targetArea: "ankle",
      title: "발목 회복 스트레칭 프로그램",
      description: "발목 가동 범위 회복 및 안정성 강화를 위한 홈 프로그램입니다.",
      exercises: stretchingLibrary.ankle,
      generalCautions: ["균형이 불안정하면 벽이나 의자를 잡고 하세요.", "부기가 있으면 아이싱 후 시행하세요."],
    },
    reportId: "report-session-P-05-1",
    chartStatus: "not_reviewed",
  },
];

export const mockChartEntries: ChartEntry[] = [
  {
    id: "chart-entry-1",
    patientId: "P-01",
    sessionId: "session-P-01-1",
    createdAt: "2026-06-25T11:00:00",
    type: "rom_measurement",
    title: "ROM 측정 결과 - 우측 손목 굴곡/신전",
    content: "치료 전 42° → 치료 후 59° (+17°, +40.5%). 통증 NRS 6→3. 유연성 78점, 안정성 82점, 신뢰도 91점.",
    includedFields: {
      romResult: true,
      painChange: true,
      clinicalSummary: true,
      stretchingEducation: true,
      followUpPlan: true,
    },
  },
  {
    id: "chart-entry-2",
    patientId: "P-01",
    sessionId: "session-P-01-1",
    createdAt: "2026-06-25T11:05:00",
    type: "education",
    title: "손목 홈 스트레칭 교육",
    content: "손목 굴곡근/신전근 스트레칭 2종 교육 완료. 하루 2회(아침, 저녁) 각 3세트 시행 권장.",
    includedFields: {
      romResult: false,
      painChange: false,
      clinicalSummary: false,
      stretchingEducation: true,
      followUpPlan: false,
    },
  },
];
