import type { PatientSession } from "./types";

export const mockPatients: PatientSession[] = [
  {
    id: "P-01",
    patientName: "김OO",
    age: 46,
    sex: "남",
    heightCm: 172,
    weightKg: 78,
    symptoms: ["통증", "가동 범위 제한", "뻣뻣함"],
    assumedDiagnosis: "손목 관절염 (de Quervain 腱炎 의심)",
    deviceWorn: true,
    deviceStatus: "connected",
    batteryPercent: 87,
    wearLocation: "wrist",
    laterality: "우측",
    attachmentMethod: "피부 부착",
    motionType: "wrist_flexion_extension",
    preRom: 42,
    postRom: 59,
    prePainNrs: 6,
    postPainNrs: 3,
    smoothnessScore: 78,
    stabilityScore: 82,
    confidenceScore: 91,
    measuredAt: "2026-06-25",
  },
  {
    id: "P-02",
    patientName: "이OO",
    age: 39,
    sex: "여",
    heightCm: 162,
    weightKg: 56,
    symptoms: ["통증", "가동 범위 제한", "운동 시 악화"],
    assumedDiagnosis: "견관절 충돌 증후군",
    deviceWorn: true,
    deviceStatus: "connected",
    batteryPercent: 72,
    wearLocation: "shoulder",
    laterality: "좌측",
    attachmentMethod: "스트랩 착용",
    motionType: "shoulder_abduction",
    preRom: 118,
    postRom: 146,
    prePainNrs: 7,
    postPainNrs: 4,
    smoothnessScore: 85,
    stabilityScore: 79,
    confidenceScore: 88,
    measuredAt: "2026-06-24",
  },
  {
    id: "P-03",
    patientName: "박OO",
    age: 57,
    sex: "여",
    heightCm: 158,
    weightKg: 62,
    symptoms: ["통증", "뻣뻣함", "야간통", "근력 저하"],
    assumedDiagnosis: "요추 추간판 탈출증 (L4-L5)",
    deviceWorn: true,
    deviceStatus: "weak",
    batteryPercent: 34,
    wearLocation: "lowerBack",
    laterality: "양측",
    attachmentMethod: "의복 위 부착",
    motionType: "lumbar_flexion",
    preRom: 38,
    postRom: 52,
    prePainNrs: 8,
    postPainNrs: 5,
    smoothnessScore: 62,
    stabilityScore: 58,
    confidenceScore: 74,
    measuredAt: "2026-06-23",
  },
  {
    id: "P-04",
    patientName: "최OO",
    age: 32,
    sex: "남",
    heightCm: 178,
    weightKg: 82,
    symptoms: ["통증", "가동 범위 제한", "움직임 불안정"],
    assumedDiagnosis: "슬관절 반월상 연골 손상 (우측)",
    deviceWorn: true,
    deviceStatus: "connected",
    batteryPercent: 95,
    wearLocation: "knee",
    laterality: "우측",
    attachmentMethod: "스트랩 착용",
    motionType: "knee_flexion",
    preRom: 96,
    postRom: 121,
    prePainNrs: 5,
    postPainNrs: 2,
    smoothnessScore: 88,
    stabilityScore: 91,
    confidenceScore: 94,
    measuredAt: "2026-06-25",
  },
  {
    id: "P-05",
    patientName: "정OO",
    age: 51,
    sex: "여",
    heightCm: 155,
    weightKg: 58,
    symptoms: ["통증", "저림", "뻣뻣함", "운동 시 악화"],
    assumedDiagnosis: "족관절 염좌 후 만성 불안정",
    deviceWorn: false,
    deviceStatus: "disconnected",
    batteryPercent: 0,
    wearLocation: "ankle",
    laterality: "좌측",
    attachmentMethod: "스트랩 착용",
    motionType: "ankle_dorsi_plantar",
    preRom: 11,
    postRom: 18,
    prePainNrs: 4,
    postPainNrs: 2,
    smoothnessScore: 55,
    stabilityScore: 61,
    confidenceScore: 68,
    measuredAt: "2026-06-22",
  },
];
